apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: s3-hello-world
          image: ghcr.io/syntasso/hello-world-s3-app:v0.1.0
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: "{{ .Values.aws.region }}"
            - name: S3_BUCKET_NAME
              value: "{{ .Values.aws.bucketName }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: accessKeyID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: secretAccessKey
          ports:
            - containerPort: 8080

